config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root :to => 'datum#index', as: :authenticated_root
    end
  end

  get 'top/index'
  root 'top#index'

  resources :datum, only: [:index, :create, :show, :new]

end

app/models/datum.rb
class Datum < ActiveRecord::Base

  VALID_DATAS_REGEX = /\A[0-9]*(,[0-9]+){1,}\z/
  validates :datas, format: { with: VALID_DATAS_REGEX }
  validates :from, numericality: {only_integer: true}
  validates :to, numericality: {only_integer: true}
  validate :check_length

  belongs_to :user
  
  serialize :datas
  serialize :results

  # リコンサイル処理を行い結果をDBに格納する。
  # リコンサイル処理が重いため、非同期処理ができるようラッパーメソッドにした。
  def reconcileUpdate(rec)
    rec.reconcile
    self.results =  rec.results
    self.save
  end

  def check_length
    
    if datas.split(",").length > 15
      errors.add(:datas, "は処理負荷の問題で、15個以上指定できません。")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :data

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datum_controller.rb
class DatumController < ApplicationController
  before_action :authenticate_user!

  def index
    @datums = Datum.where(user_id: current_user.id).order(id: :DESC).page(params[:page])
  end

  def show
    @datum = Datum.find(params[:id])

    respond_to do |format|
      format.html
      format.csv do
        filename = @datum.id.to_s + ":" + @datum.title
        headers['Content-Disposition'] = "attachment; filename=\"#{filename}.csv\""
      end
    end
    
  end

  def new
    @datum = Datum.new
  end

  def create
    @datum = Datum.new(datum_params)
    @datum.user_id = current_user.id
    @rec = Reconcile.new(@datum.datas.split(",").map{ |str| str.to_i },@datum.from.to_i,@datum.to.to_i)
    if @datum.save
      @datum.delay.reconcileUpdate(@rec)
      redirect_to datum_index_path, notice: "計算登録完了しました。"
    else
      render 'new'
    end

  end

  private
    def datum_params
      params.require(:datum).permit(:title, :from, :to, :datas)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @datum = Datum.new
  end

  private
    def datum_params
      params.require(:datum).permit(:title, :from, :to, :datas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datum_helper.rb
module DatumHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/datum/index.html.erb
<div class="container">
  <div class="intro-header2">
    <h2>計算結果一覧</h2>
    <hr>
  </div>
  <table class="table table-bordered">
    <tr class="active">
      <th>計算ID</th>
      <th>タイトル</th>
      <th>期首金額</th>
      <th>期末金額</th>
      <th>期中金額</th>
      <th>結果</th>
    </tr>
      <% @datums.each do |data| %>
        <tr>
          <td><%= data.id %></td>
          <td><%= data.title %></td>
          <td><%= data.from %></td>
          <td><%= data.to %></td>
          <td><%= data.datas %></td>
          <% if data.results.present? %>
            <td><%= link_to "HTML",datum_path(data.id) %> <%= link_to 'CSV', datum_path(data.id, format: :csv) %> <%= data.results.length %>件</td>
          <% else %>
            <td>処理中</td>
          <% end %>
        </tr>
    <% end %>
  </table>
  <%= paginate @datums %>
</div>

app/views/datum/new.html.erb
<div class="container">
  <div class="intro-header2">
    <h2>計算登録</h2>
    <hr>
  </div>
<%= form_for(@datum, url: datum_index_path ) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= @datum.errors.count %>件のエラーがあります。</h2>

        <ul>
        <% @datum.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= f.label :title%>
      <%= f.text_field :title, class:'form-control', placeholder: "タイトル", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :from %>
      <%= f.text_field :from, class:'form-control', placeholder: "開始金額", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :to %>
      <%= f.text_field :to, class:'form-control', placeholder: "終了金額", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :datas %>
      <%= f.text_field :datas, class:'form-control', placeholder: "000,000,000,...", required: true%>
    </div>
  </div>
  <div class="form-group">
    <div class="actions">
      <%= f.submit '登録', class:'btn btn-default' %>
    </div>
  </div>
<% end %>
</div>

app/views/datum/show.html.erb
<div class="container">
  <div class="intro-header2">
  <h2>計算結果</h2><%= link_to "戻る", :back %>
  <hr> 
  </div>
  <% @datum.results.each do |result| %>
    <%= result %>
    <hr>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reconciliation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
 <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="/">リコンサイル</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">

                    <% if user_signed_in? %>
                      <li><%= link_to "計算結果一覧", datum_index_path %></li>
                      <li><%= link_to "計算登録", new_datum_path %></li>
                      <li><%= link_to 'マイページ', edit_user_registration_path %></li>
                      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                      <li><%= link_to "ログイン", new_user_session_path %><li>
                      <li><%= link_to "サインアップ", new_user_registration_path %></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


<%= yield %>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Shimura Hokuto . All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

app/views/top/_form.html.erb
<%= form_for(@datum, url: datum_index_path ) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= @datum.errors.count %>件のエラーがあります。</h2>

        <ul>
        <% @datum.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= f.label :title%>
      <%= f.text_field :title, class:'form-control', placeholder: "タイトル", required: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :from %>
      <%= f.text_field :from, class:'form-control', placeholder: "開始金額" %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :to %>
      <%= f.text_field :to, class:'form-control', placeholder: "終了金額" %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :datas %>
      <%= f.text_field :datas, class:'form-control', placeholder: "000,000,000,..."%>
    </div>
  </div>
  <div class="form-group">
    <div class="actions">
      <%= f.submit '登録', class:'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/top/index.html.erb
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>リコンサイルアシスト</h1>
                        <h3>期首〜期末</h3>
                        <hr class="intro-divider">
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->